Task 1: нет, они не одинаковы. 
В первом случае ошибка обработается в блоке catch, а во втором - никак не обработается.